### ISSUE TITLE
Revised `--verbose` flag warning

### ISSUE THREAD

**Issue by thermokarst** [qiime2/q2cli#128]
Before:
```
Re-run with --verbose to see debug info.
```

After:
```
To learn more about this error, re-run with --verbose (useful when asking for help).
```

**Comment by thermokarst** [comment]
@jairideout, @ebolyen and I agreed on this language. If you have any changes/tweaks, please just follow up here. Thanks!

**Comment by jakereps** [comment]
I like the intro, but the parens portion seems _off_ to me. If that could somehow be incorporated into the intro I think it would "feel" better? Something like: 
```
To learn more about this error, and [view the full tracelog for further debugging or support] re-run with --verbose.
```

`[...]` just a random example.

**Comment by jairideout** [comment]
It might be worth explicitly mentioning the forum, since that's where this will come up most often. It also nudges users in the right direction for help (especially if they aren't aware of the forum yet).

What about something like this?

"""
Re-run with --verbose to see more details about the error. Please provide the verbose output when posting a question on the QIIME 2 forum (https://forum.qiime2.org).
"""

**Comment by thermokarst** [comment]
@jairideout, how about combing the inversion of structure from the original with a variation of your edits?

```
To learn more about this error, re-run with --verbose. Please provide the verbose output when asking for help (e.g. on the QIIME 2 forum at https://forum.qiime2.org).
```

I like providing the forum as an example (like you mentioned, raising awareness of the Q2 forum is 🎉 👍 ), but am more wary of making it *the* case, because other plugins might provide their own support resources, etc.

**Comment by ebolyen** [comment]
I *really* like the inverted structure. Also I'd prefer to avoid using too many words, because as soon as we line-wrap on this "error-bookend", we start competing with the *actual* information in the error.

The actual error should be enough information to solve the problem on it's own, so I don't want users to get the impression that it isn't their job to interpret the error and instead just post it blindly to the forum (after running w/ verbose). It's really a flaw in how we handle external binaries that make `--verbose` necessary at all. We just need to stop discarding stderr before we even know if something went wrong.

I still prefer the language in the original, because it has a friendly tone, is short, isn't specific to the forum (but plants the idea that you need this, even if just asking a friend for help), and doesn't distract you after you've read it the first time.

Those are my thoughts: :bike:-:derelict_house:

**Comment by jairideout** [comment]
All the error messages in this issue have their benefits and drawbacks. I think at this point it'd be a better use of time to resolve #127, which should make this a non-issue, or at least will change the error message to point users to error logs instead of whatever we decide here.

I think #127 is an important one to resolve for the upcoming release since error troubleshooting is already coming up a lot and that'll only continue. It's really annoying that users have to rerun a command to get more details about the error, and in many cases the error could take a long time to occur. I'm worried that users will 1) get frustrated with this behavior and wasting time debugging, and/or 2) will always include `--verbose` in their commands, which defeats the purpose of *not* showing these details to users by default.

What do you guys think about closing this issue in favor of #127?

**Comment by jairideout** [comment]
Closing in favor of #127.
