### ISSUE TITLE
Add --m-*-sep/delimiter to `MetadataCategoryHandler`

### ISSUE THREAD

**Issue by jakereps** [qiime2/q2cli#151]
Currently it isn't possible to use a CSV (or any other format) as metadata file through the cli interface. This could be another (optional `default='\t'`) option added by the `MetadataCategoryHandler` along with file and category.

**Comment by jairideout** [comment]
I'm not sure that we'd want to support other delimiters, in order to keep the metadata file format simple from an educational standpoint and to help plugin developers who may be writing their own metadata parsers (e.g. in R, C, etc.). The current QIIME 2 metadata file format is documented here:

https://docs.qiime2.org/2017.7/tutorials/metadata/#metadata-from-a-text-file

There's been some internal discussion about what delimiters other tabular file formats should use (e.g. manifest files) and we haven't landed on TSV or CSV yet (that's scheduled for the next release sprint IIRC). I think we're pretty set on using TSV for metadata though, to match QIIME 1 and for the reasons I mentioned above.

@gregcaporaso @thermokarst @ebolyen is this in line with what you're thinking?

**Comment by gregcaporaso** [comment]
> I think we're pretty set on using TSV for metadata though

I agree

**Comment by jairideout** [comment]
@jakereps @thermokarst @ebolyen and I had a call yesterday to discuss delimited formats in QIIME 2. For the near term we decided to use TSV everywhere that we can in QIIME 2, and in 2018 we can have QIIME 2 seamlessly support CSV (and other delimiters), along with Excel files and other requested formats.

Closing this issue as the framework will support sniffing and loading metadata files in a seamless way, so (ideally) interfaces such as q2cli won't need updating.
