### ISSUE TITLE
BUG: Opaque error when inappropriate value passed to primitive parameter

### ISSUE THREAD

**Issue by ChrisKeefe** [qiime2/q2cli#222]
**Bug Description**
Changes to q2cli in 2019.4 (likely [_convert_primitive](https://github.com/qiime2/q2cli/blame/master/q2cli/click/type.py)/[parse_primitive](https://github.com/qiime2/qiime2/blame/master/qiime2/core/type/util.py) are causing opaque `_COERCE_ERROR`s when users pass inappropriate values to primitive parameters. 

**Steps to reproduce the behavior**
1. Activate a `2019.4` or `2019.7.dev` Conda environment
2. Pass an inappropriate value to a command with a `--p-` parameter.
3. See terrifying error message

**Expected behavior**
A more understandable error message should be rendered. 
Falling back on the [`check_types`](https://github.com/qiime2/qiime2/blob/3e053cba101ace49ba52e16cba0bd6966973b0b3/qiime2/core/type/signature.py#L323) error messages might be nice.

**Computation Environment**
- OS: linuxMint 18.3, OpenSUSE Tumbleweed
- QIIME 2 Releases 2018.11-2019.7.dev

**Comments**
1. Impacts only `--p-` arguments
2. Does not impact Artifact API

**References**
1. Forum [xref](https://forum.qiime2.org/t/error-in-run-dada2/10523)

**Comment by Oddant1** [comment]
After playing with this a bit, I'm noticing a couple of things. First of all, it doesn't seem as though any of the methods currently raising `_COERCE_ERRORS` have access to the name of the parameter, only the value and the acceptable type(s). Second, there can be multiple acceptable types. I currently have the error message looking like this `Value 'peanut' incompatible with type(s): Int, Bool.`

**Comment by thermokarst** [comment]
> First of all, it doesn't seem as though any of the methods currently raising _COERCE_ERROR have access to the name of the parameter, only the value and the acceptable type(s)

I think one way to address this is to update the util's signature to require the caller to provide the name of the parameter. This would necessitate updating q2cli, but that isn't a big deal.

Another way to deal with this is to _not_ make this change in the framework, but rather catch the error at the calling site (for example, q2cli), and raise a new, properly worded (and interface-specific) error message there.

> Second, there can be multiple acceptable types

Totally.

> Value 'peanut' incompatible with type(s): Int, Bool.

What is the expression provided? Why not just list the type expression as-is?

**Comment by thermokarst** [comment]
Hey @Oddant1, had a good chat with @ebolyen about this, offline. So, as best we can recall, the original _intent_ for the `parse_primitive` util was to raise a signalling exception so that the interface that made the call can do whatever it wants with the exception (for example, raise a newer, better exception with more details). After trawling the stack trace linked in @ChrisKeefe's original issue comment, we noticed that q2cli does in fact attempt to catch `parse_primitive` exceptions, and then clean them up. Unfortunately, it looks like _not all of the calling sites behave that way_. Your mission is to review the stack trace above, and see what you can do about making things consistent. As always, please send your questions this direction!

**Comment by Oddant1** [comment]
It looks like this call actually does reformat the error
 
![Selection_093](https://user-images.githubusercontent.com/10642616/64037831-77699e00-cb0b-11e9-951e-a9d822ace24c.png)

And this one doesn't

![Selection_092](https://user-images.githubusercontent.com/10642616/64037770-543eee80-cb0b-11e9-8408-db7e73e9bf4f.png)
